import { FC } from "react";

export const Footer: FC = () => {
  return (
    <div className="text-center flex flex-col items-center text-xs text-zinc-700 gap-1">
      <div className="text-zinc-400">
        Responses generated by large language models. Please verify for
        accuracy.
      </div>
      <div className="text-zinc-400">
        LLM, Vector DB, and core components are powered by Netty.
      </div>
      <div className="flex gap-2 justify-center">
        {/* <div>
          <a
            className="text-blue-500 font-medium inline-flex gap-1 items-center flex-nowrap text-nowrap"
            href="mailto:zilim%ust.hk"
          >
            <Mails size={8} />
            Contact Us
          </a>
        </div> */}
        <div>Built with the support from DeepSeek-R1 ❤️</div>
      </div>

      <div className="flex items-center justify-center flex-wrap gap-x-4 gap-y-2 mt-2 text-zinc-400">
        <a className="hover:text-zinc-950" href="https://www.ust.hk/">
          HKUST Home
        </a>
        <a
          className="hover:text-zinc-950"
          href="https://github.com/OodavidsinoO/Netty-RAG"
        >
          Netty GitHub
        </a>
        <a className="hover:text-zinc-950" href="https://www.ust.hk/news">
          HKUST News
        </a>
        <a className="hover:text-zinc-950" href="https://ece.hkust.edu.hk/">
          ECE Department
        </a>
      </div>
    </div>
  );
};
